algoritmo "Contede0ate10"
Var contador : Inteiro
inicio

// Define a variável contador como 0.
   contador <- 0
// Inicia o loop enquanto contador for menor ou igual a 10.
   contador <- 0
   Enquanto (contador <= 10) faca
      EscrevaL(contador)
      contador <- contador + 1
   FimEnquanto

// Mostra na tela a mensagem "Terminei de contar" e termina o programa.
   Escreval("Terminei de contar")
fimalgoritmo